export const ExperienceList = [
  {
    company: "Xsellence Bangladesh Ltd.",
    role: "Software Developer",
    location: "Banasree, Rampura, Dhaka",
    period: "October 2025 - Present",
    type: "Current",
    responsibilities: [
      "Develop and customize modules for Sonali Aansh Ltd., primarily focused on HRM and Purchase Management workflows.",
      "Build custom features for The Daily Star Event Management System, including event booking, registration, workflow customization, access control, and security rules.",
      "Develop and customize modules for Nadia Furniture, Ultima Bangladesh HRM, and Manufacturing BOM.",
      "Develop and customize modules for Badamtoli Inventory and Sales workflow customization.",
      "Develop and customize Parking Management and Education Management systems, including operational workflows, user access, reports, and business process automation.",
      "Develop dashboards, dynamic reports, XML views, and OWL frontend components for business operations and management visibility.",
    ],
    skills: [
      "Odoo",
      "Python",
      "OWL",
      "XML",
      "HRM",
      "Purchase Management",
      "Event Management",
      "Access Control",
      "Security Rules",
      "Manufacturing BOM",
      "Inventory",
      "Sales Workflow",
      "Dashboards",
      "Dynamic Reports",
    ],
  },

  {
    company: "TEX Fasteners",
    role: "Software Developer",
    location: "Adamjee Export Processing Zone, Narayanganj",
    period: "June 2024 - October 2025",
    type: "Full Time",
    responsibilities: [
      "Developed and maintained responsive web applications using Python, Django, JavaScript, XML, and Bootstrap.",
      "Customized Odoo modules to meet business requirements across Sales, CRM, dashboards, reporting, and operational workflows.",
      "Created JavaScript-based dashboards and business transaction reporting systems for dynamic data visualization.",
      "Implemented ERP solutions to improve system integration, operational efficiency, stability, and user satisfaction.",
      "Provided ongoing support, troubleshooting, and issue resolution for ERP users and internal stakeholders.",
    ],
    skills: [
      "Python",
      "Django",
      "Odoo",
      "JavaScript",
      "Bootstrap",
      "CRM",
      "Sales",
      "Dashboard",
      "Reporting",
    ],
  },

  {
    company: "Chartered Skills Ltd.",
    role: "Web Developer",
    location: "Mirpur, Dhaka",
    period: "May 2023 - May 2024",
    type: "Full Time",
    responsibilities: [
      "Developed responsive websites using HTML, CSS, JavaScript, and React.js with cross-browser and mobile compatibility.",
      "Translated wireframes and design mockups into functional web pages aligned with brand and business objectives.",
      "Integrated backend APIs using Django and Express.js and connected databases including MySQL and MongoDB.",
      "Supported WordPress web applications and dynamic content management requirements.",
    ],
    skills: [
      "React.js",
      "HTML",
      "CSS",
      "JavaScript",
      "Django",
      "Express.js",
      "MySQL",
      "MongoDB",
      "WordPress",
    ],
  },
];